#!/usr/bin/env python3
"""
Compute profile-reduced CSP and generate M2 Nullstellensatz degree script.

Reads CSP dump from circuit-presheaf `profiles --m2gen` output.
Computes edge profiles to reduce domain elements to interchangeable classes.
Generates M2 script to compute NS degree.

Usage:
  python3 ns_from_csp.py CSP_DUMP_FILE [OUTPUT_M2_FILE]
"""

import sys
from collections import defaultdict

def parse_csp(filename):
    """Parse CSP dump file into nodes and edges."""
    nodes = {}  # nodeIdx -> domSize
    edges = []  # list of (nodeI, nodeJ, groupsI, groupsJ)

    current_edge = None
    current_gi = {}
    current_gj = {}

    with open(filename) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            if line.startswith("NODES "):
                pass  # just count
            elif line.startswith("NODE "):
                parts = line.split()
                nodes[int(parts[1])] = int(parts[2])
            elif line.startswith("EDGE "):
                # Save previous edge
                if current_edge is not None:
                    edges.append((current_edge[0], current_edge[1], current_gi, current_gj))
                parts = line.split()
                current_edge = (int(parts[1]), int(parts[2]))
                current_gi = {}
                current_gj = {}
            elif line.startswith("GI "):
                # Format: GI <canonical_key> <idx1> <idx2> ...
                parts = line.split()
                key = parts[1]
                indices = [int(x) for x in parts[2:]]
                current_gi[key] = indices
            elif line.startswith("GJ "):
                parts = line.split()
                key = parts[1]
                indices = [int(x) for x in parts[2:]]
                current_gj[key] = indices

    # Save last edge
    if current_edge is not None:
        edges.append((current_edge[0], current_edge[1], current_gi, current_gj))

    return nodes, edges

def compute_profiles(nodes, edges):
    """Compute edge profiles for each node.

    A profile = tuple of (edgeIdx, canonicalKey) for all edges involving this node.
    Elements with the same profile are interchangeable.
    """
    # Build per-node edge key maps: node -> list of (edgeIdx, {domIdx: key})
    node_edge_keys = defaultdict(list)

    for eidx, (ni, nj, gi, gj) in enumerate(edges):
        # Invert groupsI: domIdx -> key for node ni
        inv_i = {}
        for key, indices in gi.items():
            for idx in indices:
                inv_i[idx] = key
        node_edge_keys[ni].append((eidx, inv_i))

        # Invert groupsJ: domIdx -> key for node nj
        inv_j = {}
        for key, indices in gj.items():
            for idx in indices:
                inv_j[idx] = key
        node_edge_keys[nj].append((eidx, inv_j))

    # Compute profiles per node
    profiles = {}  # nodeIdx -> {profileTuple: [domIdx, ...]}
    profile_keys = {}  # nodeIdx -> {profileIdx: {edgeIdx: key}}

    for ni, dom_size in nodes.items():
        edge_keys = node_edge_keys[ni]
        # Sort edges by index for consistent profiles
        edge_keys.sort(key=lambda x: x[0])

        prof_groups = defaultdict(list)
        for dom_idx in range(dom_size):
            profile = tuple(
                (eidx, inv.get(dom_idx, "?"))
                for eidx, inv in edge_keys
            )
            prof_groups[profile].append(dom_idx)

        # Assign profile indices
        sorted_profiles = sorted(prof_groups.keys())
        profiles[ni] = {}
        profile_keys[ni] = {}
        for pidx, prof in enumerate(sorted_profiles):
            profiles[ni][pidx] = prof_groups[prof]
            # Extract edge -> key mapping from the profile tuple
            profile_keys[ni][pidx] = {eidx: key for eidx, key in prof}

    return profiles, profile_keys

def generate_m2_script(nodes, edges, profiles, profile_keys):
    """Generate M2 script for NS degree computation."""
    lines = []
    lines.append("-- NS degree computation (profile-reduced CSP)")
    lines.append("-- Generated by ns_from_csp.py")
    lines.append("")

    # Variable names
    var_names = []
    for ni in sorted(profiles.keys()):
        for pidx in sorted(profiles[ni].keys()):
            var_names.append(f"x{ni}p{pidx}")

    nv = len(var_names)
    lines.append(f"R = QQ[{','.join(var_names)}];")
    lines.append("")

    # Build constraint list
    constraints = []

    # Boolean constraints: x^2 - x = 0
    for v in var_names:
        constraints.append(f"{v}^2 - {v}")

    # Selection constraints: sum(x_{i,*}) - 1 = 0
    for ni in sorted(profiles.keys()):
        vars_i = [f"x{ni}p{pidx}" for pidx in sorted(profiles[ni].keys())]
        constraints.append(" + ".join(vars_i) + " - 1")

    # Incompatibility constraints: x_{i,a} * x_{j,b} = 0 for incompatible pairs
    n_incompat = 0
    for eidx, (ni, nj, gi, gj) in enumerate(edges):
        for pi in sorted(profile_keys[ni].keys()):
            for pj in sorted(profile_keys[nj].keys()):
                key_i = profile_keys[ni][pi].get(eidx, "?")
                key_j = profile_keys[nj][pj].get(eidx, "?")
                if key_i != "?" and key_j != "?" and key_i != key_j:
                    constraints.append(f"x{ni}p{pi}*x{nj}p{pj}")
                    n_incompat += 1

    lines.append(f"-- {nv} variables, {len(constraints)} constraints ({n_incompat} incompatibility)")
    lines.append("I = ideal(")
    for i, c in enumerate(constraints):
        sep = "," if i < len(constraints) - 1 else ""
        lines.append(f"  {c}{sep}")
    lines.append(");")
    lines.append("")

    # NS degree computation
    lines.append(f'print("vars: {nv}");')
    lines.append(f'print("generators: " | toString(numgens I));')
    lines.append('print("1 in I: " | toString(1 % I == 0));')
    lines.append("")
    lines.append("-- Compute NS degree by checking degree-d certificates")
    lines.append("-- (This may be slow for large systems)")
    lines.append('-- for d from 1 to 10 do (')
    lines.append('--   gb = gb(I, DegreeLimit => d);')
    lines.append('--   if 1 % ideal(flatten entries gb) == 0 then (')
    lines.append('--     print("NS degree <= " | toString(d));')
    lines.append('--     break;')
    lines.append('--   );')
    lines.append('-- );')

    return "\n".join(lines)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 ns_from_csp.py CSP_DUMP_FILE [OUTPUT_M2_FILE]")
        sys.exit(1)

    csp_file = sys.argv[1]
    nodes, edges = parse_csp(csp_file)

    print(f"Parsed: {len(nodes)} nodes, {len(edges)} edges")
    total_elems = sum(nodes.values())
    print(f"Total domain elements: {total_elems}")

    profiles, profile_keys = compute_profiles(nodes, edges)

    total_profiles = sum(len(p) for p in profiles.values())
    print(f"\nProfile reduction:")
    for ni in sorted(profiles.keys()):
        print(f"  node {ni}: {nodes[ni]} elements -> {len(profiles[ni])} profiles")
    print(f"Total variables: {total_profiles} (from {total_elems})")

    # Count incompatible pairs
    n_incompat = 0
    for eidx, (ni, nj, gi, gj) in enumerate(edges):
        for pi in profile_keys[ni]:
            for pj in profile_keys[nj]:
                ki = profile_keys[ni][pi].get(eidx, "?")
                kj = profile_keys[nj][pj].get(eidx, "?")
                if ki != "?" and kj != "?" and ki != kj:
                    n_incompat += 1
    print(f"Incompatibility constraints: {n_incompat}")

    if len(sys.argv) >= 3:
        m2_file = sys.argv[2]
        script = generate_m2_script(nodes, edges, profiles, profile_keys)
        with open(m2_file, 'w') as f:
            f.write(script)
        print(f"\nM2 script written to: {m2_file}")
        print(f"Run: M2 --script {m2_file}")

    # Also try solving the reduced CSP with backtracking
    print("\n--- Solving reduced CSP ---")
    solution = solve_reduced(profiles, profile_keys, edges)
    if solution is not None:
        print(f"SAT: {solution}")
    else:
        print("UNSAT (exhaustive search)")

def solve_reduced(profiles, profile_keys, edges):
    """Backtracking solver on the profile-reduced CSP."""
    node_order = sorted(profiles.keys(), key=lambda ni: len(profiles[ni]))

    def is_consistent(assignment, ni, pi):
        for eidx, (ei, ej, _, _) in enumerate(edges):
            if ei == ni and ej in assignment:
                ki = profile_keys[ni][pi].get(eidx, "?")
                kj = profile_keys[ej][assignment[ej]].get(eidx, "?")
                if ki != "?" and kj != "?" and ki != kj:
                    return False
            elif ej == ni and ei in assignment:
                ki = profile_keys[ei][assignment[ei]].get(eidx, "?")
                kj = profile_keys[ni][pi].get(eidx, "?")
                if ki != "?" and kj != "?" and ki != kj:
                    return False
        return True

    def backtrack(idx, assignment):
        if idx == len(node_order):
            return dict(assignment)
        ni = node_order[idx]
        for pi in sorted(profiles[ni].keys()):
            if is_consistent(assignment, ni, pi):
                assignment[ni] = pi
                result = backtrack(idx + 1, assignment)
                if result is not None:
                    return result
                del assignment[ni]
        return None

    return backtrack(0, {})

if __name__ == "__main__":
    main()
