#!/usr/bin/env python3
"""
Resolution width analysis for structural CSP instances.

Converts the profile-reduced compatibility CSP to CNF clauses and computes
the minimum-width resolution refutation. For UNSAT instances, this measures
the proof complexity: resolution width Ω(n) would imply circuit lower bounds
via the Ben-Sasson–Wigderson size-width tradeoff.

Usage:
  python3 resolution_width.py CSP_DUMP_FILE [--dimacs FILE.cnf] [--solve] [--width]

Modes:
  --dimacs FILE.cnf   Export DIMACS CNF file
  --solve             Solve the CNF via DPLL (small instances only)
  --width             Measure resolution width via BFS (small instances only)
"""

import sys
import os
from collections import defaultdict

# Reuse parser and profile computation from ns_from_csp
sys.path.insert(0, os.path.dirname(__file__))
from ns_from_csp import parse_csp, compute_profiles

def build_cnf(profiles, profile_keys, edges):
    """Build CNF clauses from the profile-reduced CSP.

    Variables: x_{node,profile} encoded as positive integers.
    Returns (num_vars, clauses) where each clause is a list of signed ints.
    """
    # Assign variable numbers: (node, profile) -> var (1-indexed)
    var_map = {}
    var_count = 0
    for ni in sorted(profiles.keys()):
        for pidx in sorted(profiles[ni].keys()):
            var_count += 1
            var_map[(ni, pidx)] = var_count

    clauses = []

    # At-least-one: for each node, at least one profile is selected
    for ni in sorted(profiles.keys()):
        clause = [var_map[(ni, pidx)] for pidx in sorted(profiles[ni].keys())]
        clauses.append(clause)

    # At-most-one: for each node, no two profiles selected simultaneously
    for ni in sorted(profiles.keys()):
        pidxs = sorted(profiles[ni].keys())
        for i in range(len(pidxs)):
            for j in range(i + 1, len(pidxs)):
                clauses.append([-var_map[(ni, pidxs[i])], -var_map[(ni, pidxs[j])]])

    # Incompatibility: for each edge, incompatible profile pairs are forbidden
    for eidx, (ni, nj, gi, gj) in enumerate(edges):
        for pi in sorted(profile_keys[ni].keys()):
            for pj in sorted(profile_keys[nj].keys()):
                key_i = profile_keys[ni][pi].get(eidx, "?")
                key_j = profile_keys[nj][pj].get(eidx, "?")
                if key_i != "?" and key_j != "?" and key_i != key_j:
                    clauses.append([-var_map[(ni, pi)], -var_map[(nj, pj)]])

    return var_count, clauses, var_map


def write_dimacs(filename, num_vars, clauses):
    """Write DIMACS CNF file."""
    with open(filename, 'w') as f:
        f.write(f"c Profile-reduced structural CSP\n")
        f.write(f"c Generated by resolution_width.py\n")
        f.write(f"p cnf {num_vars} {len(clauses)}\n")
        for clause in clauses:
            f.write(" ".join(str(lit) for lit in clause) + " 0\n")


def dpll_solve(clauses, assignment=None):
    """Simple DPLL solver. Returns assignment dict or None."""
    if assignment is None:
        assignment = {}

    # Unit propagation
    changed = True
    clauses = [list(c) for c in clauses]
    while changed:
        changed = False
        new_clauses = []
        for clause in clauses:
            # Remove false literals
            reduced = [lit for lit in clause if -lit not in assignment or not assignment[-lit]]
            # Check if satisfied
            satisfied = any(lit in assignment and assignment[lit] for lit in clause)
            if satisfied:
                continue
            reduced = [lit for lit in clause
                       if abs(lit) not in {abs(k) for k in assignment}
                       or (lit > 0 and assignment.get(lit, None) is True)
                       or (lit < 0 and assignment.get(-lit, None) is False)]
            # Re-evaluate
            active = [lit for lit in clause if abs(lit) not in {abs(k) for k in assignment}]
            sat = False
            for lit in clause:
                v = abs(lit)
                if v in assignment:
                    if (lit > 0 and assignment[v]) or (lit < 0 and not assignment[v]):
                        sat = True
                        break
            if sat:
                continue
            unset = [lit for lit in clause
                     if abs(lit) not in assignment]
            if len(unset) == 0:
                return None  # conflict
            if len(unset) == 1:
                # Unit clause: propagate
                lit = unset[0]
                v = abs(lit)
                assignment[v] = (lit > 0)
                changed = True
            else:
                new_clauses.append(clause)
        clauses = new_clauses

    # Check if all clauses satisfied
    if not clauses:
        return assignment

    # Pick a variable to branch on (first unassigned in first clause)
    var = abs(clauses[0][0])
    for val in [True, False]:
        new_assign = dict(assignment)
        new_assign[var] = val
        result = dpll_solve(clauses, new_assign)
        if result is not None:
            return result
    return None


def resolution_step(c1, c2, var):
    """Resolve c1 and c2 on variable var. Returns resolvent or None."""
    if var in c1 and -var in c2:
        resolvent = set(c1) | set(c2)
        resolvent.discard(var)
        resolvent.discard(-var)
        # Check for tautology
        for lit in resolvent:
            if -lit in resolvent:
                return None
        return frozenset(resolvent)
    if -var in c1 and var in c2:
        resolvent = set(c1) | set(c2)
        resolvent.discard(var)
        resolvent.discard(-var)
        for lit in resolvent:
            if -lit in resolvent:
                return None
        return frozenset(resolvent)
    return None


def measure_resolution_width(clauses, max_width=None, max_clauses=500000):
    """Measure minimum resolution width to derive the empty clause.

    Uses iterative widening: try to derive empty clause using only
    clauses of width <= w, for w = 1, 2, 3, ...

    Returns (width, num_derived) or None if couldn't derive empty clause.
    """
    initial = set()
    for c in clauses:
        initial.add(frozenset(c))

    all_vars = set()
    for c in clauses:
        for lit in c:
            all_vars.add(abs(lit))

    if max_width is None:
        max_width = len(all_vars)

    for w in range(0, max_width + 1):
        # Try to derive empty clause using clauses of width <= w
        known = set(c for c in initial if len(c) <= w)
        queue = list(known)
        derived = 0

        while queue:
            if derived > max_clauses:
                break
            c1 = queue.pop(0)
            for var in all_vars:
                for c2 in list(known):
                    if c1 is c2:
                        continue
                    resolvent = resolution_step(c1, c2, var)
                    if resolvent is not None and len(resolvent) <= w:
                        if resolvent not in known:
                            known.add(resolvent)
                            queue.append(resolvent)
                            derived += 1
                            if len(resolvent) == 0:
                                return w, derived
                            if derived > max_clauses:
                                break
                if derived > max_clauses:
                    break

        # Check if empty clause was derived at this width
        if frozenset() in known:
            return w, derived

        print(f"  width {w}: {len(known)} clauses ({derived} derived), no refutation", file=sys.stderr)

    return None


def measure_width_ordered(clauses, max_clauses=1000000):
    """Measure resolution width using ordered resolution (complete for Horn-like).

    Derives all resolvents breadth-first, tracking the maximum clause width
    in the shortest derivation of the empty clause.
    """
    initial = set()
    for c in clauses:
        initial.add(frozenset(c))

    all_vars = set()
    for c in clauses:
        for lit in c:
            all_vars.add(abs(lit))

    # BFS: each level adds all possible resolvents
    known = set(initial)
    frontier = list(initial)
    max_width_seen = max(len(c) for c in initial)
    generation = 0
    total_derived = 0

    while frontier:
        generation += 1
        new_clauses = set()

        for c1 in frontier:
            for var in all_vars:
                for c2 in known:
                    resolvent = resolution_step(c1, c2, var)
                    if resolvent is not None and resolvent not in known:
                        new_clauses.add(resolvent)
                        if len(resolvent) == 0:
                            return max_width_seen, total_derived + len(new_clauses)

        if not new_clauses:
            break

        total_derived += len(new_clauses)
        max_width_in_gen = max(len(c) for c in new_clauses) if new_clauses else 0
        max_width_seen = max(max_width_seen, max_width_in_gen)

        print(f"  gen {generation}: +{len(new_clauses)} clauses (max width {max_width_in_gen}, "
              f"total {len(known) + len(new_clauses)})", file=sys.stderr)

        if total_derived > max_clauses:
            print(f"  clause limit reached ({max_clauses})", file=sys.stderr)
            break

        known |= new_clauses
        frontier = list(new_clauses)

    if frozenset() in known:
        return max_width_seen, total_derived
    return None


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    csp_file = sys.argv[1]
    do_dimacs = None
    do_solve = False
    do_width = False

    i = 2
    while i < len(sys.argv):
        if sys.argv[i] == "--dimacs" and i + 1 < len(sys.argv):
            do_dimacs = sys.argv[i + 1]
            i += 2
        elif sys.argv[i] == "--solve":
            do_solve = True
            i += 1
        elif sys.argv[i] == "--width":
            do_width = True
            i += 1
        else:
            i += 1

    # Parse CSP
    nodes, edges = parse_csp(csp_file)
    print(f"Parsed: {len(nodes)} nodes, {len(edges)} edges")
    total_elems = sum(nodes.values())
    print(f"Total domain elements: {total_elems}")

    # Compute profiles
    profiles, profile_keys = compute_profiles(nodes, edges)
    total_profiles = sum(len(p) for p in profiles.values())
    print(f"Profiles: {total_profiles} (from {total_elems} elements)")
    for ni in sorted(profiles.keys()):
        print(f"  node {ni}: {nodes[ni]} -> {len(profiles[ni])} profiles")

    # Build CNF
    num_vars, clauses, var_map = build_cnf(profiles, profile_keys, edges)
    alo_count = len(profiles)
    amo_count = sum(len(p) * (len(p) - 1) // 2 for p in profiles.values())
    incompat_count = len(clauses) - alo_count - amo_count
    print(f"\nCNF: {num_vars} variables, {len(clauses)} clauses")
    print(f"  at-least-one: {alo_count}")
    print(f"  at-most-one: {amo_count}")
    print(f"  incompatibility: {incompat_count}")

    # Export DIMACS
    if do_dimacs:
        write_dimacs(do_dimacs, num_vars, clauses)
        print(f"\nDIMACS written to: {do_dimacs}")

    # Solve
    if do_solve:
        print("\n--- DPLL Solver ---")
        result = dpll_solve(clauses)
        if result is not None:
            print("SAT")
            # Show assignment per node
            for ni in sorted(profiles.keys()):
                for pidx in sorted(profiles[ni].keys()):
                    v = var_map[(ni, pidx)]
                    if result.get(v, False):
                        print(f"  node {ni} -> profile {pidx} (domain elements: {profiles[ni][pidx]})")
        else:
            print("UNSAT")

    # Resolution width
    if do_width:
        print("\n--- Resolution Width ---")
        if num_vars > 50:
            print(f"WARNING: {num_vars} variables may be too large for exact resolution width")
            print("Consider using a sub-instance")

        print("Measuring resolution width (iterative widening)...")
        result = measure_resolution_width(clauses, max_clauses=500000)
        if result is not None:
            width, n_derived = result
            print(f"Resolution width: {width}")
            print(f"Clauses derived: {n_derived}")
        else:
            print("Could not derive empty clause within limits")

    if not do_dimacs and not do_solve and not do_width:
        print("\nUse --dimacs FILE, --solve, or --width to do something with the CNF")


if __name__ == "__main__":
    main()
